### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by aman-bhatia** [hlzz/libvot#12]
I am not able to install the library.

I do not have nvidia graphics card so I cmake using
`cmake -DLIBVOT_USE_CUDA=OFF -DLIBVOT_USE_CUDNN=OFF ..`

then while I `make`, I got the following error
![screenshot from 2016-09-22 17-45-37](https://cloud.githubusercontent.com/assets/8138598/18747765/93cd8dac-80ec-11e6-8515-281812cf1c2e.png)

Help pls!

**Comment by hlzz** [comment]
It seems that glog is not linking the right gflags. Thanks for the report. I will look into that later.

**Comment by hlzz** [comment]
@aman-bhatia hi, this bug should be fixed. pls checkout the latest commit. Thanks for your report.

**Comment by hlzz** [comment]
I will just close this issue. Feel free to leave a message here if you encounter any other problems. :)
