### ISSUE TITLE
 Match only in a determined range of the tree

### ISSUE THREAD

**Issue by jokla** [hlzz/libvot#13]
Hi! 
I was trying to use libvot for a problem of vision-based localization. I built a database using image_search from a collection of training pictures (a continuous recording of a street path). After I have a new continuous sequence of pictures (the test), recorded along the same path. At the first iteration, I want to find the closest match using the first pictures of the test set. For this, I used web_search and I find the best match (let's call it A). In order to speed-up the process, I would like to run another search, using the second picture of the test set, but only in a neighbor of the previous result A. Is it possible with libvot?

Thanks!

**Comment by hlzz** [comment]
@jokla Hi, I think what you describe here is called query expansion. If that is, you can refer to query_expansion to see if there is something useful for your need. Actually web_search and image_search just act like examples of how this repo works. For your question, I think you can query the db one time, then rank and save the result, and query the db a second time, using the APIs shown in the example code.
