### ISSUE TITLE
cmake cannot find -lopencv_dep_cudart

### ISSUE THREAD

**Issue by hlzz001** [hlzz/libvot#14]
system: ubuntu 16.04

[ 42%] Linking CXX shared library ../../lib/libvot_feature.so
/usr/bin/ld: cannot find -lopencv_dep_cudart
collect2: error: ld returned 1 exit status
src/feature/CMakeFiles/vot_feature.dir/build.make:145: recipe for target 'lib/libvot_feature.so.0.1' failed
make[2]: *** [lib/libvot_feature.so.0.1] Error 1
CMakeFiles/Makefile2:355: recipe for target 'src/feature/CMakeFiles/vot_feature.dir/all' failed
make[1]: *** [src/feature/CMakeFiles/vot_feature.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by hlzz** [comment]
The latest commit fixes this issue. This issue is similar to https://github.com/opencv/opencv/issues/6542
