### ISSUE TITLE
是否支持vs编译器？

### ISSUE THREAD

**Issue by wanghai1988** [hlzz/libvot#15]
是否支持vs编译器？

**Comment by pmoulon** [comment]
English version? (compiler?)

**Comment by wanghai1988** [comment]
Whether to support Visual Studio compiler variants

**Comment by hlzz** [comment]
@wanghai1988 I haven't tested it on windows. So the simple answer is that it currently doesn't support vs compiler. But you can go ahead and try if it works on windows machine :)
