### ISSUE TITLE
pull-request: small speed improvement

### ISSUE THREAD

**Issue by cdcseacave** [hlzz/libvot#2]
Thanks for the great work: fast and good results!

Please find attached a small patch improving a bit the speed and memory usage by replacing IndexedFloat with a static plane index array. I fixed also some warnings.

[patch.zip](https://github.com/hlzz/libvot/files/74376/patch.zip)

**Comment by hlzz** [comment]
Thanks a lot for the patch. Would you like to submit a pull request? That would be easier for me to updated the code. Thanks.

**Comment by cdcseacave** [comment]
Sorry, I do not to submit a pull request without forking the project, and I do not plan to do that.

But I do not know what you mean by "easier". Applying the path is as easy as running:
```
git apply patch.diff
```

**Comment by hlzz** [comment]
Thanks, I will try it.
