### ISSUE TITLE
Error with gtest

### ISSUE THREAD

**Issue by AIBluefisher** [hlzz/libvot#20]
In the installation guide, sudo apt-get install libgtest-dev cannot be used directly, for just the source code is installed into /usr/include, but the static libraries are required of gtest. I recommend to install gtest from source. https://www.cnblogs.com/lynch_world/archive/2011/12/08/2281335.html is a reference link.

**Comment by hlzz** [comment]
@AIBluefisher Thanks. Which version of OS are you using? I have just tested it on my 14.04 and 16.04 ubuntu machines and it works fine. Anyway, manually setup the dependencies is an option.
