### ISSUE TITLE
Why not use VGG?

### ISSUE THREAD

**Issue by coollofty** [hlzz/libvot#21]
I only found a SIFT features matcher....
 generally, the accuracy for SIFT about 50%, and VGG can upto 90%, why not use VGG?

**Comment by hlzz** [comment]
@coollofty I don't fully understand your question. Do you mean using VGG for image retrieval. Then I guess what you describe here is a different method from this (vocabulary tree). Using VGG and other neural net models is the state-of-the-art for global image retrieval, but it's not the scope of this repo.
