### ISSUE TITLE
I cannot run bin/libvot_feature as instructed

### ISSUE THREAD

**Issue by alexs7** [hlzz/libvot#24]
I am trying to run ```./libvot_feature image_list``` and I get this:

```
dyld: Library not loaded: /usr/local/opt/openblas/lib/libopenblasp-r0.3.5.dylib
Referenced from: /usr/local/opt/opencv@3/lib/libopencv_core.3.4.dylib
Reason: image not found
```

Any help ?

**Comment by hlzz** [comment]
@alexs7 hi, It seems that you have a version conflict of opencv. You may remove one or reinstall it.

**Comment by alexs7** [comment]
Ok that that mean I should delete one of them ? I am not sure why it is looking for `libopenblasp` in opencv..

**Comment by alexs7** [comment]
Ok! update I run `homebrew update `and `homebrew upgrade` and it works now! thanks!
